options( encoding = "UTF-8" )
source("./Setup/libriaries.R")
source("./Ui/ui.R", encoding = "UTF-8")
source("./Ui/uiSetup.R", encoding = "UTF-8")
source("./Server/graph.R", encoding = "UTF-8")
source("./Server/timeNet.R", encoding = "UTF-8")
source("./Server/hateReply.R", encoding = "UTF-8")
source("./Server/valueBoxes.R", encoding = "UTF-8")
source("./Server/classification.R", encoding = "UTF-8")